MusicBook/config/routes.rb
Rails.application.routes.draw do
  resources :favourites, only: [:destroy]
  resources :playlist_songs
  resources :playlists

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :artists
    resources :genres
    resources :albums
    resources :songs
    root :to => "dashboards#index", as: :root
  end

  resources :genres, only: [:index]

  root 'home#index'


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get '/artists' => 'artists#index', as: :artists_home
  get '/artist/:id' => 'artists#show', as: :artist_show

  get '/albums' => 'albums#index', as: :albums_home
  get '/album/:id' => 'albums#show', as: :album_show

  get '/genres' => 'genres#index', as: :genres_home
  get '/genre/:id' => 'genres#show', as: :genre_show

  get '/songs' => 'home#songs', as: :songs_home

  get '/playlists' => 'home#playlists', as: :playlists_home
  get '/favourites' => 'home#favourites', as: :favourites_home

  get '/playlists/:id/songs' => 'playlists#playlist_songs', as: :playlist_songs_list

  get 'home/addOrRemoveSongFromFavourites/:id' => 'home#addOrRemoveSongFromFavourites', as: :addOrRemoveSongFromFavourites
  
end

MusicBook/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

MusicBook/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
end

MusicBook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicBook/app/models/artist.rb
class Artist < ApplicationRecord
end

MusicBook/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

MusicBook/app/models/genre.rb
class Genre < ApplicationRecord
end

MusicBook/app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
end

MusicBook/app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
    has_many :playlist_songs
end

MusicBook/app/models/song.rb
class Song < ApplicationRecord
  paginates_per 20
  belongs_to :artist
  belongs_to :album
  belongs_to :genre
  has_many :playlist_songs

  scope :search, -> (search) { where('name LIKE ?', "%#{search}%").order(:created_at) }

  scope :trending, -> (top) {joins("INNER JOIN favourites ON favourites.song_id = songs.id").group("songs.id").order("count(favourites.song_id) desc").take(top)}

end

MusicBook/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  ROLE_USER = 0
  ROLE_ADMIN = 1
  ROLE_SUPER_ADMIN = 2

  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email

  def admin?
    role == ROLE_ADMIN
  end

  def superadmin?
    role == ROLE_SUPER_ADMIN
  end

end

MusicBook/app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
  end

  def new
    @album = Album.new
  end

  def edit
  end


  def create
    @album = Album.new(album_params)
    @album.user_id = cookies[:user_id]

      if @album.save
        redirect_to admin_album_path(@album), notice: 'Album was successfully created.' 
      else
        render :new 
      end
  end

  def update
      if @album.update(album_params)
        redirect_to admin_album_path(@album), notice: 'Album was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @album.destroy
      redirect_to admin_albums_path, notice: 'Album was successfully destroyed.' 
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name, :year, :artist_id)
    end
end

MusicBook/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show]

  def index
    params[:action] = 'albums'
    @albums = Album.all
  end

  def show
    @songs = Song.where(:album_id => params[:id])
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

end

MusicBook/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :set_artist, only: [:show]

  def index
        params[:action] = 'artists'
    @artists = Artist.all
  end

  def show
    @albums = Album.where(:artist_id => params[:id])
    @songs = Song.where(:artist_id => params[:id])
  end

    private
    def set_artist
      @artist = Artist.find(params[:id])
    end

end

MusicBook/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show]

  def index
    params[:action] = 'genres'
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @songs = Song.where(:genre_id => params[:id])
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end
end

MusicBook/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    p params[:search]
    @songs = Song.search(params[:search]).page params[:page]
    @trending = Song.trending(10)
    @albums = Album.order(:created_at).take(5)
  end

  def songs
    params[:action] = 'songs'
    @songs = Song.order(:created_at).page params[:page]
  end

  def favourites
        params[:action] = 'favourites'
        @favourites = Favourite.all
  end

  def addOrRemoveSongFromFavourites

    @favourites = Favourite.where(:user_id => cookies[:user_id], :song_id => params[:id])
    if(@favourites.count > 0 )
        @favourites.destroy_all
        msg = { :status => "ok", :message => "Success!", :action => "Add to favourites" }
        render :json => msg 
    else

    @favourite = Favourite.new
    @favourite.song_id = params[:id]
    @favourite.user_id = cookies[:user_id]

    if @favourite.save
        msg = { :status => "ok", :message => "Success!", :action => "Remove from favourites" }
        render :json => msg      
        else
        msg = { :status => "ok", :message => "Error!", :action => "" }
        render :json => msg 
      end
    end
  end

end

MusicBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Registered successfully!'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

MusicBook/app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

MusicBook/app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash(type)
    if flash[type]
      content_tag :div, nil, class: 'alert alert-success' do
        content_tag :p, flash[type]
      end
    end
  end

  def message_for_number(number, tag = :h1)
    result = number > 3 ? 'veci' : 'manji'
    content_tag tag.to_sym, "Broj je #{result} od 3"
  end

  def error_for(attribute, errors, &block)
    if errors[attribute].any?
      content_tag :p, nil, class: 'validation-error' do
        yield("#{parse_attribute(attribute)} #{errors[attribute][0]}") if block_given?
        "#{parse_attribute(attribute)} #{errors[attribute][0]}"
      end
    end
  end

  def parse_attribute(attribute)
    attribute.to_s.capitalize.split('_').join(' ')
  end

  def navbar_link(options)
    content_tag :li, nil, class: params[options[action]] do
      content_tag :p, flash[type]
    end
  end
end

MusicBook/app/helpers/artists_helper.rb
module ArtistsHelper
end

MusicBook/app/helpers/favourites_helper.rb
module FavouritesHelper
end

MusicBook/app/helpers/genres_helper.rb
module GenresHelper
end

MusicBook/app/helpers/playlist_songs_helper.rb
module PlaylistSongsHelper
end

MusicBook/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

MusicBook/app/helpers/songs_helper.rb
module SongsHelper
end

MusicBook/app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album] do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this admin_album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :album_name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :album_year %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.collection_select :artist_id, Artist.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MusicBook/app/views/admin/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', admin_album_path(@album) %> |
<%= link_to 'Back', admin_albums_path %>

MusicBook/app/views/admin/albums/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <div class="panel-heading"><h4>Albums </h4><%= link_to 'New Album', new_admin_album_path %></div>
  <div class="panel-body">
    <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= album.year %></td>
        <td><%= album.artist.name %></td>
        <% if album.user_id == current_user.id %>
        <td><%= link_to 'Show', admin_album_path(album) %></td>
        <td><%= link_to 'Edit', edit_admin_album_path(album) %></td>
        <td><%= link_to 'Destroy', admin_album_path(album), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

MusicBook/app/views/admin/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', admin_albums_path %>

MusicBook/app/views/admin/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<%= link_to 'Back', admin_albums_path %>

MusicBook/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-success">
  <div class="panel-heading"><h1>Albums </h1></div>
  <div class="panel-body">
    <table class="table">
  <thead>
    <tr>
    <th>Photo</th>
      <th>Name</th>
      <th>Year</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
          <td><%= image_tag "albumimage.jpg" %>
          </td>
        <td><%= album.name %></td>
        <td><%= album.year %></td>
        <td><%= link_to album.artist.name, artist_show_path(album.artist) %></td>
        <td><%= link_to 'Show', album_show_path(album) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

MusicBook/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
  <div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <% if logged_in? %>
    <%= render 'shared/playlist_song' %>
    <% end %>
  </div>
<div class="jumbotron">
  <h1><%= @album.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist.name %>
</p>
</div>

<div class="panel panel-success">
  <div class="panel-heading"><h4>Songs </h4>
</div>
  <div class="panel-body">

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Duration</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.artist.name %></td>
        <td><%= song.album.name %></td>
        <td><%= song.genre.name %></td>
        <td><%= song.duration %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<%= link_to 'All albums', albums_home_path %>
