MusicBook/config/routes.rb
Rails.application.routes.draw do
  resources :favourites, only: [:destroy]
  resources :playlist_songs
  resources :playlists

  namespace :admin do
    resource :dashboard, only: [:show]
    resources :artists
    resources :genres
    resources :albums
    resources :songs
    root :to => "dashboards#index", as: :root
  end

  resources :genres, only: [:index]

  root 'home#index'


  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get '/artists' => 'artists#index', as: :artists_home
  get '/artist/:id' => 'artists#show', as: :artist_show

  get '/albums' => 'albums#index', as: :albums_home
  get '/album/:id' => 'albums#show', as: :album_show

  get '/genres' => 'genres#index', as: :genres_home
  get '/genre/:id' => 'genres#show', as: :genre_show

  get '/songs' => 'home#songs', as: :songs_home

  get '/playlists' => 'home#playlists', as: :playlists_home
  get '/favourites' => 'home#favourites', as: :favourites_home

  get '/playlists/:id/songs' => 'playlists#playlist_songs', as: :playlist_songs_list

  get 'home/addOrRemoveSongFromFavourites/:id' => 'home#addOrRemoveSongFromFavourites', as: :addOrRemoveSongFromFavourites
  
end

MusicBook/app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

MusicBook/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
end

MusicBook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicBook/app/models/artist.rb
class Artist < ApplicationRecord
end

MusicBook/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

MusicBook/app/models/genre.rb
class Genre < ApplicationRecord
end

MusicBook/app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
end

MusicBook/app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
    has_many :playlist_songs
end

MusicBook/app/models/song.rb
class Song < ApplicationRecord
  paginates_per 20
  belongs_to :artist
  belongs_to :album
  belongs_to :genre
  has_many :playlist_songs

  scope :search, -> (search) { where('name LIKE ?', "%#{search}%").order(:created_at) }

  scope :trending, -> (top) {joins("INNER JOIN favourites ON favourites.song_id = songs.id").group("songs.id").order("count(favourites.song_id) desc").take(top)}

end

MusicBook/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  ROLE_USER = 0
  ROLE_ADMIN = 1
  ROLE_SUPER_ADMIN = 2

  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email

  def admin?
    role == ROLE_ADMIN
  end

  def superadmin?
    role == ROLE_SUPER_ADMIN
  end

end

MusicBook/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show]

  def index
    params[:action] = 'albums'
    @albums = Album.all
  end

  def show
    @songs = Song.where(:album_id => params[:id])
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

end

MusicBook/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show]

  def index
    params[:action] = 'genres'
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @songs = Song.where(:genre_id => params[:id])
  end

  private
    def set_genre
      @genre = Genre.find(params[:id])
    end
end

MusicBook/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    p params[:search]
    @songs = Song.search(params[:search]).page params[:page]
    @trending = Song.trending(10)
    @albums = Album.order(:created_at).take(5)
  end

  def songs
    params[:action] = 'songs'
    @songs = Song.order(:created_at).page params[:page]
  end

  def favourites
        params[:action] = 'favourites'
        @favourites = Favourite.all
  end

  def addOrRemoveSongFromFavourites

    @favourites = Favourite.where(:user_id => cookies[:user_id], :song_id => params[:id])
    if(@favourites.count > 0 )
        @favourites.destroy_all
        msg = { :status => "ok", :message => "Success!", :action => "Add to favourites" }
        render :json => msg 
    else

    @favourite = Favourite.new
    @favourite.song_id = params[:id]
    @favourite.user_id = cookies[:user_id]

    if @favourite.save
        msg = { :status => "ok", :message => "Success!", :action => "Remove from favourites" }
        render :json => msg      
        else
        msg = { :status => "ok", :message => "Error!", :action => "" }
        render :json => msg 
      end
    end
  end

end

MusicBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Registered successfully!'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
  end
end

MusicBook/app/helpers/application_helper.rb
module ApplicationHelper
  def display_flash(type)
    if flash[type]
      content_tag :div, nil, class: 'alert alert-success' do
        content_tag :p, flash[type]
      end
    end
  end

  def message_for_number(number, tag = :h1)
    result = number > 3 ? 'veci' : 'manji'
    content_tag tag.to_sym, "Broj je #{result} od 3"
  end

  def error_for(attribute, errors, &block)
    if errors[attribute].any?
      content_tag :p, nil, class: 'validation-error' do
        yield("#{parse_attribute(attribute)} #{errors[attribute][0]}") if block_given?
        "#{parse_attribute(attribute)} #{errors[attribute][0]}"
      end
    end
  end

  def parse_attribute(attribute)
    attribute.to_s.capitalize.split('_').join(' ')
  end

  def navbar_link(options)
    content_tag :li, nil, class: params[options[action]] do
      content_tag :p, flash[type]
    end
  end
end

MusicBook/app/helpers/artists_helper.rb
module ArtistsHelper
end

MusicBook/app/helpers/favourites_helper.rb
module FavouritesHelper
end

MusicBook/app/helpers/genres_helper.rb
module GenresHelper
end

MusicBook/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

MusicBook/app/helpers/songs_helper.rb
module SongsHelper
end

MusicBook/app/views/layouts/admin.html.erb
<style>
  .active {
    background: red;
  }
</style>

<!DOCTYPE html>
<html>
  <head>
    <title>MusicBook | Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      </head>

  <body>
    <div class="">
      <nav class="navbar navbar-default">
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Back to site', root_path %></li>
            <li><%= link_to 'Artists', admin_artists_path %></li>
            <li><%= link_to 'Genres', admin_genres_path %></li>
            <li><%= link_to 'Album', admin_albums_path %></li>
            <li><%= link_to 'Songs', admin_songs_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">Logged in as: <%= current_user.username %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user.admin? || current_user.superadmin? %>
              <li><%= link_to 'Dashboard', admin_dashboard_path %></li>
            <% end %>
            <li><%= link_to 'Logout', session_path, method: :delete %></li>
          </ul>
        </li>
        

          </ul>
        </div>
      </nav>

      <div class="container">
      <%= yield %>
      </div>
    </div>
  </body>
</html>

MusicBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>

  <body style="background-image: url('assets/images/background.jpg'); ">
    <%= render 'shared/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>